### ISSUE TITLE
Is this not irresponsible disclosure?

### ISSUE THREAD

**Issue by acdemiralp** [fedden/poker_ai#101]
If you realize an open source Pluribus, is it not going to break online poker? People will abuse it to the maximum and it will take years for online poker companies to adjust. Cheating in online poker is going to become an arms race between the abusers which take this repository as a base and the companies, like it is today in video games / anti-cheat software. Except that online poker involves real money and not some bytes corresponding to your in-game outfit.

I understand that you are looking for a cool thing to put on your resume, but this is a terrible idea. The authors of the original paper have not released the source code to the public for good reason. 

For the note, I am also implementing Pluribus, although privately, and for research purposes. There obviously is nothing I can do to stop you, but have you asked these, perhaps not so obvious questions to yourself prior to starting this project? Because I have, and decided to keep it private. I would like to hear your counter-arguments.

**Comment by JonathanLehner** [comment]
Someone will use it sooner or later. at least it is fair if the code is available to everyone.

**Comment by big-c-note** [comment]
Hey @acdemiralp . Thanks for raising your concern. I won't speak for @fedden , but I can speak for myself here. 

Firstly, the intention of this project is to implement core ideas for poker AI in general. The main motivation is purely academic as there is no money being made from this project. 

I won't speak to whether or not I think it's ethical to break online poker, but I will say it is impossible to without significant adjustments to this code base. 

Currently, we only support a 20 card short deck and limit-style betting. By my estimation it is physically impossible to cluster the card combinations required to do a 52 card deck without implementing other ideas that we decided to leave out (although I will say we were able to develop them 💯 ).

**Comment by crclayton** [comment]
You can't uninvent technology or suppress a project like this; someone will eventually make it. If you look at chess for comparison, stockfish is only one of many open-source chess engines that now can routinely beat top players. Overall, chess engines have been a net positive for the game since people can use them to learn and find previously unexplored ways of playing, and there are also engine vs. engine competitions that are really exciting. There have been some controversies about professionals or amateurs using engines to cheat in tournaments, but players are monitored and penalized like any other form of cheating in any game/sport, and it's far from breaking the game.

Again, some strategies for detecting engine cheaters that are used in chess websites (and tournaments with cash on the line) are monitoring click activity, monitoring for consistent time intervals between decisions (moves), scrutinizing "unnatural" moves, using faster time controls, comparing decisions to popular engine decisions, stuff like that.

**Comment by acdemiralp** [comment]
In retrospect, I agree such knowledge should be out in the open, but I am not going to open source mine due to personal interest.

Any sane online chess tournament does not involve monetary gain for the exact reason that chess engines exist. All the other detection arrays you mentioned are merely for non-monetary matches - to keep it fair. There are thousands of online poker venues which very much involve monetary gain though. If you have a working Pluribus right now, you can make several thousand every day without much hassle. And who am I to say anything about it.

**Comment by crclayton** [comment]
> Any sane online chess tournament does not involve monetary gain for the exact reason that chess engines exist.

Well for what it's worth this isn't true and hasn't been for a while, but particularly not over the last year when all the in-person tournaments have been cancelled. There have been lots of online tournaments with significant prize money involved. 

Though I agree that it's a weak comparison since prize-money chess certainly isn't the standard like it is with poker, but just practically speaking someone's going to make an AI at some point, and likely already has, and it's up to the platforms to catch cheaters rather than programmers to not build things.

**Comment by B3g** [comment]
@acdemiralp who guarantees that you are not here to make the moral, but only because having installed pluribus, you do not want others to have the same chance as you, a game and honest as long as everyone has the same possibility, so the open source solution is the best solution
